### ISSUE TITLE
centos环境下安装Nodejs报错，请问是什么原因呢？

### ISSUE THREAD

**Issue by 99937272** [izuolan/dockerfiles#3]
root@845b6350ce7a:/workspace/env# ./run.sh
0. 基础软件包
1. 扩展软件包
2. Nodejs
3. Python(pip)
4. Golang
5. Java
6. PHP+Apache
7. Tomcat
8. MySQL
第一次执行请安装基础软件包，然后选择其他操作。
选择你要安装的开发环境（输入前面的数字）：2
./run.sh: line 102: sudo: command not found
./run.sh: line 103: sudo: command not found
v7.8.0

**Comment by izuolan** [comment]
这是Cloud9-ide镜像吗？
执行`apt-get install sudo`即可。
